image: markhobson/maven-chrome:jdk-11

test:
  stage: Smoke
  script:
    - mvn clean install
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/allure-report
    expire_in: 1 week
  only:
    - master
